version: '3.1'

services:
    php:
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - 5555:80
      volumes:
          - ./public:/var/www/html

    db:
      image: mariadb
      restart: always
      environment:
            MYSQL_DATABASE: tp_combat
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
    
    phpmyadmin:
      image: phpmyadmin
      restart: always
      depends_on:
        - db
      ports:
          - 8080:80
      environment:
          - PMA_ARBITRARY=1
